// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://agmtwmpchnqxunfkcnur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFnbXR3bXBjaG5xeHVuZmtjbnVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5NjI0ODcsImV4cCI6MjA1ODUzODQ4N30.fi6jhjV6kA328gW9aEK5bqoqw0vwjRV1j31TPN6SjnQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});